### ISSUE TITLE
Suggest language change to match IANA "collected" vs. "publishedd"

### ISSUE THREAD

**Issue by hardie** [jariarkko/draft-arkko-trip-registry-update#1]
The document currently says:

   Contact information relating to a registration will no longer be
   required to include postal address.  In addition, the IANA is
   instructed that displaying previously collected postal address
   information should be deprecated.

IANA has started to use the distinction between "collected" and "published" to distinguish information that IANA has vs. that which is displayed.  I think we could use that language here:

IANA will no longer collect postal address information when adding TRIP registry entries. Additionally, IANA should no longer publish previously collected postal addresses.

**Comment by jariarkko** [comment]
Yes. Will modify. (Do you btw want to be a co-author?)

**Comment by hardie** [comment]
I think having a co-author on something this short is silly, but thanks.

Ted
